<?php
session_start();
$title = "Deploy Static Site";
include('./includes/header.php');
include_once('./config/dbConfig.php');
error_reporting(E_ALL);
ini_set('display_errors', 1);
?>

<?php
$upload_dir = 'uploads/';
if($_SERVER['REQUEST_METHOD'] == 'POST'){
    if(isset($_POST['submit'])){
        $sitename = $_POST['sitename'];
        $port = $_POST['port'];
        if(isset($_FILES['sitezip'])){
            $targetFile = $_SERVER['DOCUMENT_ROOT'] . "/" . $upload_dir . basename($_FILES['sitezip']['name']);
            $file_ext = pathinfo($targetFile,PATHINFO_EXTENSION);

            if($file_ext == 'zip'){
                if(move_uploaded_file($_FILES['sitezip']['tmp_name'], $targetFile)){
                    if($port == 80){

                        $deployment_dir = '/var/www/html/'.$sitename."/";
                        $zip = new ZipArchive();
                        if($zip->open($targetFile) == TRUE){
                            $zip->extractTo($deployment_dir);
                            $zip->close();
                            unlink($targetFile);
                            echo "<script>alert('Deployment Successfull')</script>";
                        }
                    }
                    else
                    { 
                       $deployment_dir = '/var/www/'.$port."/";
                       $zip = new ZipArchive();

                       if($zip->open($targetFile) == TRUE){
                        $zip->extractTo($deployment_dir);
                        $zip->close();

                        echo "extracion complete";
                        $uri = "$uri";
                        $nginx_conf = "server {
    listen $port default_server;
    listen [::]:$port default_server;

    # SSL configuration
    #
    # listen 443 ssl default_server;
    # listen [::]:443 ssl default_server;
    #
    # Note: You should disable gzip for SSL traffic.
    # See: https://bugs.debian.org/773332
    #
    # Read up on ssl_ciphers to ensure a secure configuration.
    # See: https://bugs.debian.org/765782
    #
    # Self signed certs generated by the ssl-cert package
    # Don't use them in a production server!
    #
    # include snippets/snakeoil.conf;

    root $deployment_dir;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html index.php;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri /=404;
    }

    # pass PHP scripts to FastCGI server
    #
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
    #
    #   # With php-fpm (or other unix sockets):
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
    #   # With php-cgi (or other tcp sockets):
    #   fastcgi_pass 127.0.0.1:9000;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny all;
    }
}
";
                        $nginx_conf_file = '/etc/nginx/sites-available/default';
                       $cmd = "echo \"$nginx_conf\" | sudo tee -a $nginx_conf_file > /dev/null";
                        $write_cmd = shell_exec($cmd);

                        if($write_cmd == null){
                            echo "written succesfull";
                        }

                        
                        // $restart_cmd = shell_exec("sudo systemctl restart nginx.service");

                        // if($restart_cmd == null){
                        //     unlink($targetFile);
                        //     echo "<script>alert('Deployment Successfull')</script>";
                        // }
                    }
                }
            }
            else
            {
                echo "<script>alert('Unable to Upload the file')</script>";
            }
        }
    }
}
}


?>

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <?php include('./includes/sidebar.php')?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <?php include('./includes/navbar.php')?>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mb-4 text-gray-800">Deploy Static Site</h1>

                <div class="row">

                    <div class="col-lg-8">

                        <!-- Student card -->
                        <div class="card shadow mb-4">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">Enter Details to Add New Website</h6>
                            </div>
                            <div class="card-body">
                             <form action="" method="post" id="user-form" enctype="multipart/form-data">
                                 <div class="col-lg-10">
                                     <div class="mb-2">
                                      <label for="exampleFormControlInput1" class="form-label">Site Name</label>
                                      <input type="text" class="form-control" id="exampleFormControlInput1" name="sitename">
                                  </div>
                                  <div class="mb-2">
                                      <label for="exampleFormControlInput1" class="form-label">Port Number</label>
                                      <input type="text" class="form-control" id="exampleFormControlInput1" name="port" placeholder="Eg. 8080" value="80">
                                  </div>
                                  <p class="text-danger mb-1">* Please Upload Zip file only *</p>
                                  <div class="my-3">
                                    <input type="file" name="sitezip" accept=".zip">
                                </div>

                            </div>
                            <div>
                                <button class="btn btn-primary" name="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById("user-form").addEventListener("submit", function(event) {
            var formData = new FormData(this);
            if (
                formData.get("sitename").trim() === "" ||
                formData.get("port").trim() === "" ||
                formData.get('sitezip').name === ""
                ) {
                alert("Please fill in all required fields.");
            event.preventDefault(); // Prevent form submission
        }
    });
    });
</script>

<?php include('./includes/footer.php')?>